# Generated by Django 4.2.6 on 2023-12-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarpad', '0004_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret_answer',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret_question',
            field=models.CharField(blank=True, choices=[('q1', 'What is your favorite color?'), ('q2', 'In which city were you born?'), ('q3', 'What is the name of your best friend?')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
