# Generated by Django 4.2.6 on 2023-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarpad', '0005_userprofile_phone_number_userprofile_secret_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HighScore',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
