# Generated by Django 4.2.6 on 2024-01-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarpad', '0007_delete_quizscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='secret_answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secret_question',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
